services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: poetry run gunicorn bookStore.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
    - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=bookstore
      - POSTGRES_DB=bookstore
  nginx:
    build: build/nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
      - 8080:80
    depends_on:
      - web
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
        - ~/.docker-conf/redis/data/:/var/lib/redis/
        - ~/.docker-conf/redis/log/:/var/log/redis
  celery_worker:
    container_name: celery_worker
    build: .
    command: poetry run celery -A bookStore worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
  flower:
    container_name: flower
    build: .
    command: poetry run celery -A bookStore flower --port=5555
    ports:
      - 5556:5555
    depends_on:
      - web
      - redis
      - celery_worker
      
volumes:
  postgres_data:
  static_volume:
  media_volume: