# Generated by Django 5.0.4 on 2024-05-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        ("genres", "0001_initial"),
        ("languages", "0001_initial"),
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "publication_year",
                    models.IntegerField(verbose_name="Publication Year"),
                ),
                ("pages", models.IntegerField(verbose_name="Num of Pages")),
                (
                    "isbn",
                    models.CharField(
                        max_length=22, verbose_name="International Standard Book Number"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("authors", models.ManyToManyField(to="authors.author")),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="genres.genre"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="languages.language",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="publishers.publisher",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
