# Generated by Django 5.0.4 on 2024-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=70, unique=True, verbose_name="Name"),
        ),
    ]
